Settings:
    Bungeecord:
        Enabled: false
        Lobby: lobby
    Timers:
        Waiting: 30
        WaitingFull: 10
        WinLenght: 10
    Chat:
        Lobby: '&8[&e{coins}&8&l] &7{player} &8» &7{message}'
        Game: '&8[&e{team}&8&l] &7{player} &8» &7{message}'
        WaitingLobby: '&7{player} &8» &7{message}'
        Spectator: '&cSpectator &c» &7{player} &8» &7{message}'
    Commands:
        Whitelist:
            Enabled: true
            Allowed:
            - bridge
            - hub
            - lobby
            - msg
            - tell
            - w
            - tp
            - list
            - stafflist
            - report
        Kill:
        - mysterydust add {killer} 3 msg=false
        Win:
        - mysterydust add {player} 50 msg=false
    NameTags:
        Lobby:
            Main: '&7'
            Waiting: '&7'
    Rewards:
        Win:
            Coins: 5
        Kill:
            Coins: 20
    Game-Status:
        WAITING: '&aWaiting...'
        IN-GAME: '&cIN-GAME'
        STARTING: '&bStarting...'
        RESTARTING: '&cEnding...'
    Misc:
        Start-Hearts: 2
        Per-Arena-Tablist: true
    Leaderboards:
        Type: SKULLS
        EmptyPlaceReplace: Loading...
        SmallArmorStand: true
    Sounds:
        Kill:
            Sound: ORB_PICKUP
            Volume: 1.0
            Pitch: 1.0
        JoinGame:
            Sound: LEVEL_UP
            Volume: 1.0
            Pitch: 1.0
        StartingGame:
            Sound: LEVEL_UP
            Volume: 1.0
            Pitch: 1.0
        NeedMorePlayers:
            Sound: ANVIL_BREAK
            Volume: 1.0
            Pitch: 1.0
        ReceiveArrow:
            Sound: NOTE_PLING
            Volume: 1.0
            Pitch: 1.0

MySQL:
    Enabled: false
    Host: localhost
    Port: 3306
    Username: root
    Password: test
    Database: mysql
    Tablename: bridge_stats
    Use_ssl: false

Teams:
    Blue:
        Name: '&1Blue'
        NameTag: '&1B &7'
        Color: '&1'
        Item:
            Logo: blue clay
            Cage: blue glass
    Red:
        Name: '&cRed'
        NameTag: '&cR &7'
        Color: '&c'
        Item:
            Logo: red clay
            Cage: red glass
    Yellow:
        Name: '&eYellow'
        NameTag: '&eY &7'
        Color: '&e'
        Item:
            Logo: yellow clay
            Cage: yellow glass
    Green:
        Name: '&aGreen'
        NameTag: '&aG &7'
        Color: '&a'
        Item:
            Logo: green clay
            Cage: green glass

Items:
    Teleporter:
        Name: '&8» &aPlay teleporter &7(Right Click)'
        Item: compass
        Slot: 0
        Lore:
        - ''
    Spectator-Settings:
        Name: '&8» &bSpectator Settings &7(Right Click)'
        Item: redstone comparator item
        Slot: 4
        Lore:
        - ''
    Leave:
        Name: '&8» &6Leave the game'
        Item: magma cream
        Slot: 8
        Lore:
        - ''
    Team-Selector:
        Name: '&8» &6Team Selector &7(Right Click)'
        Item: chest
        Slot: 0
        Lore:
        - ''
    Play:
        Name: '&8» &3Play &7(Right Click)'
        Item: diamond axe
        Slot: 0
        Lore:
        - ''
    Shop:
        Name: '&8» &3Shop &7(Right Click)'
        Item: anvil
        Slot: 3
        Lore:
        - ''
    HotbarEditor:
        Name: '&8» &aLayout Editor  &7(Right Click)'
        Item: item frame
        Slot: 5
        Lore:
        - ''
    Lobby-Leave:
        Name: '&8» &6Leave the lobby &7(Right Click)'
        Item: magma cream
        Slot: 8
        Lore:
        - ''
    Custom-Item:
        Name: '&8» &7EXAMPLE'
        Item: air
        Slot: 9
        Lore:
        - ''
        Command: example command
